title: Awesome Civic Tech
description: Una lista colaborativa y curada de proyectos de tecnología cívica en México.

sass:
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - Applications
  - case-studies
  - open-source-policies
  - procurement
  - security

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

theme: jekyll-theme-primer
permalink: pretty
